services:
  db:
    container_name: postgres
    image: postgres:14.1
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5332:5432"
    networks:
      - db
    restart: unless-stopped

  spring-boot-application:
    container_name: spring-boot-application
    image: kuzmanoski/sprig-boot-application
    ports:
      - "8082:8082"
    networks:
      - db
    depends_on:
      - db
    restart: unless-stopped
    command: ["--spring.datasource.url=jdbc:postgresql://db:5432/customer"]

  react-application:
    container_name: react-application
    image: kuzmanoski/react-application
    build:
      context: frontend/react
      args:
        api_based_url: http://localhost:8082
    ports:
      - "3000:5173"
    depends_on:
      - spring-boot-application
    restart: unless-stopped

networks:
  db:
    driver: bridge

volumes:
  db: